# Dependencies
markdown:	            redcarpet
highlighter:	        pygments

# Permalinks
permalink:	            pretty
relative_permalinks:	true

# Setup
title:	                FauDroids
description:	        'The Android challenge:<br>1 year, 12 months, 12 Android Apps'
tagline:	            'FauDroids'
url:	                http://faudroids.org/

paginate:	            5
github:                 https://github.com/FauDroids?tab=repositories
