# Dependencies
markdown:	            redcarpet
highlighter:	        pygments

# Permalinks
permalink:	            pretty
relative_permalinks:	true

# Setup
title:	                FauDroids
description:	        'The Android challenge:<br>1 year, 12 months, 12 Android Apps'
tagline:	            'FauDroids'
url:	                http://FauDroids.github.io/

# Post authors
authors:
    philipp:
        name:	        Philipp Eichhorn
        display_name:	Philipp
        email:	        philipp.eichhorn@bitdroid.de
        github:	        https://github.com/Maddoc42

paginate:	            5

github:
  repo:	                https://github.com/FauDroids/
