# Dependencies
markdown:	            redcarpet
highlighter:	        pygments

# Permalinks
permalink:	            pretty
relative_permalinks:	true

# Setup
title:	                FauDroids
description:	        'The Android challenge:<br>1 year, 12 months, 12 Android Apps'
tagline:	            'FauDroids'
url:	                http://FauDroids.github.io/

# Post authors
authors:
    philipp:
        name:	        Philipp Eichhorn
        role:	        Software Developer
        message:	    Hi there! My name is Philipp and I am studying computer science here in Germany. Make sure to drop me a note in case you find some of the projects interesting!
        email:	        philipp.eichhorn@bitdroid.de
        github:	        Maddoc42
        homepage:	    http://bitdroid.de

paginate:	            5

github:
  repo:	                https://github.com/FauDroids?tab=repositories
